### ISSUE TITLE
add authentication via Google

### ISSUE THREAD

**Issue by jacoblxliu** [JakePickle/teamform-seed#11]
This is our proposed feature#1 in milestone #1.
Corresponding button elements have been added to the interface, but they are not functioning for now.
According to TA, we may only implement one of the two.

**Comment by JakePickle** [comment]
I'm working on setting up the host for the site as I think that is necessary to test the google login.

**Comment by JakePickle** [comment]
I set up the aws with LAMP and Git but we need to register the domain of our site with google to use their login api. I'm not sure we can do this as we don't actually own a domain name.

**Comment by jacoblxliu** [comment]
https://firebase.google.com/docs/auth/web/google-signin
https://firebase.google.com/docs/auth/web/facebook-login
Are these the references you used?

Public hostname of the instance cannot be used as the domain?

**Comment by JakePickle** [comment]
Those are not the references I used. I will try to use those.

**Comment by JakePickle** [comment]
that was an accident.
