### ISSUE TITLE
Problems in profile editing

### ISSUE THREAD

**Issue by suyanzhe** [JakePickle/teamform-seed#32]
- The education selection (namely the item "undergraduate") is inconsistent.
- What-if people with lower education level want to join the system?
- Duplicated code across dashboard.html and profile.html is a bad design; make maintenance difficult

**Comment by suyanzhe** [comment]
This could move to "blocked" until more frontend code are complete according to the discussions in #30...

**Comment by jacoblxliu** [comment]
then just move it...

**Comment by suyanzhe** [comment]
Seems that I cannot move because I don't have the "teamform-seed collaborator" privilege.

**Comment by jacoblxliu** [comment]
Ok i did it

**Comment by suyanzhe** [comment]
Moved to #88
