### ISSUE TITLE
Unexpected text input on index.html

### ISSUE THREAD

**Issue by jacoblxliu** [JakePickle/teamform-seed#95]
![capture](https://cloud.githubusercontent.com/assets/16507109/20567075/5f8f1c42-b1d2-11e6-8c91-7dd2f3966965.PNG)

**Comment by JakePickle** [comment]
The Facebook button should also not be there. I think these may have been introduced in my last PR. I can fix them.

**Comment by jacoblxliu** [comment]
facebook button could be there as a dummy button. It looks better. we don't have to implement the connect function anyway.

**Comment by JakePickle** [comment]
I just got rid of it. I can put it back.

**Comment by JakePickle** [comment]
There is no text box though, this must be an older version of index.html.
